name: CI/CD-Backend Pipeline

on: [push, pull_request]

jobs:
  ci-backend:

    runs-on: ubuntu-latest
    outputs:
      ci-successful: ${{ steps.ci-backend.outputs.success }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Run tests
      run: |
        cd app
        python -m unittest ./tests/test_app.py

  cd-Backend:
    if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for CI-Backend to finish
      if: success()
      run: echo "CI-Backend successfully finished"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build --platform linux/amd64/v2 -t enricogoerlitz/bp2-backend-amd64v2 -f ./docker/Dockerfile .

    - name: Push Docker image
      run: |
        docker push enricogoerlitz/bp2-backend-amd64v2:latest